//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoncharovVympelSale.AppFolder.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientEnterPC
    {
        public int ClientEnterPC_ID { get; set; }
        public int ClientID { get; set; }
        public string NamePC { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
