//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoncharovCarPartsAS.AppFolder.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportOfStaff
    {
        public int PassportOfStaffID { get; set; }
        public Nullable<int> StaffID { get; set; }
        public int PassportID { get; set; }
    
        public virtual Passport Passport { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
