//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoncharovCarPartsAS.AppFolder.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        public int ProducGroupID { get; set; }
        public int OrderID { get; set; }
        public int ProductOrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ProductOrder ProductOrder { get; set; }
    }
}
