//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoncharovCarPartsAS.AppFolder.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int StorageID { get; set; }
        public int DepartamentID { get; set; }
        public int ProductID { get; set; }
        public int Amount { get; set; }
        public string StorageNum { get; set; }
        public int StatusProductID { get; set; }
    
        public virtual DepartamentCompany DepartamentCompany { get; set; }
        public virtual Product Product { get; set; }
        public virtual StatusProduct StatusProduct { get; set; }
    }
}
